default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: exercise_app_development
test:
  <<: *default
  database: exercise_app_test

production:
  <<: *default
  database: exercise_app_production
  username: exercise_app
  password: <%= Rails.application.credentials.config[:EXERCISE_APP_DATABASE_PASSWORD] %>
